---
# tasks file for team.apache
- name: install package
  dnf:
          name: "{{ web_var }}"
          state: latest
- name: start
  service:
           name: "{{ web_var }}"
           state: started
           enabled: yes
- name: template
  template:
           src: /home/lisa/ansible/apache.j2
           dest: /tmp/xxy
           owner: root
           group: root
           mode: 0644
  notify: restart httpd

