---
# tasks file for web-role
- name: install software
  dnf:
          name: httpd
          state: latest

- name: start services
  service:
          name: httpd
          state: started
          enabled: yes

- name: install software
  firewalld:
             service: http
             state: enabled
             permanent: yes
             immediate: yes

- name: template
  template:
           src: web.j2
           dest: /var/www/html/index.html
